classdef AT_SystemType
    enumeration
        linear1D
        circular1D
        square2D
        hexagonal2D
        hexagonalSphere2D
        triangular2D
        triangularSphere2D
        grided2D
        cubic2D
        cubicSphere2D
        randomUniformFlat2D
        randomUniformSphere2D
        randomQuasiFlat2D
        randomQuasiSphere2D
        randomQuasiFlatRB2D
    end
end
